export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto py-10 px-4">
      <h1 className="text-3xl font-bold mb-8 text-center">Terms & Conditions</h1>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Acceptance of Terms</h2>
        <p>By using WriteFlow AI, you agree to these Terms & Conditions. If you do not agree, please do not use our service.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Use of Service</h2>
        <p>You may use WriteFlow AI for lawful purposes only. Prohibited uses include unauthorized access, reverse engineering, or distributing harmful content.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">AI-Generated Content</h2>
        <p>Content generated by WriteFlow AI is for informational purposes. You are responsible for reviewing and using AI-generated content appropriately.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Subscription & Billing</h2>
        <p>Some features require a paid subscription. By subscribing, you agree to our billing terms and authorize recurring charges as described at checkout.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Termination</h2>
        <p>We may suspend or terminate your access for violations of these terms or misuse of the service. You may cancel your account at any time.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Limitation of Liability</h2>
        <p>WriteFlow AI is provided "as is" without warranties. We are not liable for damages arising from your use of the service or AI-generated content.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-lg font-semibold mb-2">Changes to Terms</h2>
        <p>We may update these Terms & Conditions at any time. Continued use of WriteFlow AI after changes constitutes acceptance of the new terms.</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold mb-2">Contact</h2>
        <p>For questions about these terms, contact us at <a href="mailto:hello@writeflow.ai" className="text-primary underline">hello@writeflow.ai</a>.</p>
      </section>
    </div>
  );
}
